apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100000
globalDefault: false
description: "this priority clas is used for high-priority pods."
preemptionPolicy: preemptLowerPriority