apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: rps-1
  labels:
    app: app1
    tier: tier-1
spec:
  selector:
    matchLabels:
      tier: tier-1
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: tier-1
        app: app1
    spec:
      containers:
      - name: nginx
        image: nginx